### PR TITLE
Fix TeamCity 2018 errors

### LINKED ISSUE #30: Difficulty correlating TeamCity build with artifact
The build name that is assigned to the artifact is difficult to reproduce in TeamCity and makes build promotion difficult.

The problem is [this line of code](https://github.com/JFrogDev/teamcity-artifactory-plugin/blob/2.4.0/server/src/main/java/org/jfrog/teamcity/server/runner/ArtifactoryBuildStartContextProcessor.java#L114)

```
runnerContext.addRunnerParameter(BUILD_NAME, build.getFullName());
```

Should be 

```
runnerContext.addRunnerParameter(BUILD_NAME, build.getBuildTypeId());
```

That value returned by `build.getBuildTypeId()` is exposed as a variable in TeamCity `%system.teamcity.buildType.id%`. As far as I can see there is no way to get the value of `build.getFullName()` easily.

### PR DESCRIPTION
**Pull request by casz**
Had to fix assembly since it was broken after pom changes.

Use of External ID instead of full name should provide a safer linking.

To fix older build uploads Artifactory lucky provides a feature for that in their API
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-BuildRename we suggest users follow this route.
We plan to provide a script that can go through all builds via REST.
I haven't seen the same option in groovy user scripts for Artifactory.

fixes #30 #43 #46 

CC @eyalbe4 @pavel-spacil @TCAgentUser @DimaNevelev

### CODE REVIEW

**Comment by eyalbe4** [comment]
You're right @casz!
Let me fix this quickly...

**Comment by casz** [comment]
@eyalbe4 I'll rebase/revert my change then once I got your fix 👍

**Comment by eyalbe4** [comment]
Done. I pushed [this](https://github.com/jfrog/teamcity-artifactory-plugin/commit/c84724b175c6495c5015718c874a9987ed9acb56) commit which fixes this.

**Comment by casz** [comment]
Removed our commit and removed the section in the desc about the error 😅

**Comment by eyalbe4** [comment]
Thanks @casz!
I'm going over this now.
In the meantime, can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N)?
We need this so that we're allowed to merge the code.

**Comment by eyalbe4** [comment]
Thanks so much @casz!

**Comment by casz** [comment]
@eyalbe4 When you package it now you have to do it from the parent POM. Otherwise it will provide you with zip structured just as before 👍

**Pull request merged**
